version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000

  nginx:
    image: nginx:latest
    networks:
      - my_network
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount custom Nginx config

networks:
  my_network:
